global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "gateway-rest"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway-rest:8000"]

  - job_name: "processor-rest"
    metrics_path: /metrics
    static_configs:
      - targets: ["processor-rest:8000"]

  - job_name: "gateway-grpc"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway-grpc:8000"]

  - job_name: "processor-grpc"
    metrics_path: /metrics
    static_configs:
      - targets: ["processor-grpc:9102"]